server {
    listen 80;
    server_name localhost;

    include /etc/nginx/conf.d/error-pages.conf;

    location / {
        return 404;
    }
    location /403 { return 403; }
    location /500 { return 500; }
    location /502 { return 502; }
    location /503 { return 503; }
    location /429 { return 429; }
}
